### ISSUE TITLE
CustomUser Scaffold

### ISSUE THREAD

**Issue by propenster** [propenster/internio#2]
Hey Josh,

Spin up a CustomUser scaffold..that we can then link to the Django Allauth I was using for the overall auth before??? just CustomUser for authentication adding fields like Github, Linkedin, and particulary UserLocation

**Comment by joshajiniran** [comment]
Setting up a CustomUser after migrations in Django is an uphill task, with circular dependency issues, very challenging. However, it can be achieved by starting afresh with no migrations or creating a UserProfile model as a One-to-One link with the existing User model. What do you say?

**Comment by propenster** [comment]
Yes let's do it Bro... Create UserProfile and make a relationship with the exisiting User..Model... This will even solve our Company Reg and Auth problem we discussed yesterday...

**Comment by joshajiniran** [comment]
Ok, so, I already spun up the UserProfile, tested it and it worked. It's in a new branch

I also started an accounts app, added the CustomUser model, but I haven't linked it nor migrated. I figured out we can still set up the CustomUser since we are using sqlite for now, when we prepare to integrate Postgres, it will be the first migration according to the recommendation to avoid dependency issues. So are still on point for a go.

**Comment by joshajiniran** [comment]
Yeah, I installed flake8 for proper code formatting (pep8 standards), so do a pipenv install, also I moved the internio folder up the directory, instead of internio/internio/project-codes-and-files, it's now internio/project-codes-and-files. removed the redundancy, so kindly update. Keep me updated. Thanks

**Comment by propenster** [comment]
Josh Baba... You are a ninja! Well done Bro... You are the CEO/CTO here now
if this thing works... nice one Bro...

**Comment by joshajiniran** [comment]
CustomUser should work now in docker configured project, not yet tested extensively though.

**Comment by propenster** [comment]
Weldone Josh Baba !

Nice work!
On Mar 18, 2021 6:26 PM, "Josh Ajiniran" ***@***.***> wrote:

CustomUser should work now in docker configured project, not yet tested
extensively though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/propenster/internio/issues/2#issuecomment-802144699>,
or unsubscribe
